# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: skillsunionsaravanan
# "service" is the name of this project. This will also be added to your AWS resource names.
service: continueintegration
#frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  aws-region: us-east-1 
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get


plugins:
  - serverless-offline