# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: skillsunionsaravanan
# "service" is the name of this project. This will also be added to your AWS resource names.
service: sara-continueintegration
#frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1 
functions:
  hello:
    handler: handler.hello
    environment:
      CLASS_NAME: "CE6_sara"
    events:
      - httpApi:
          path: /
          method: get
resources:
  Resources:
    saraEmailSns:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: sara-email-topic
        Subscription: 
          - Protocol: "email"
            Endpoint: "saravanannus@gmail.com"

plugins:
  - serverless-offline