# This is the name of the workflow
name: CICD with serverless

# The run-name dynamically shows who triggered the workflow
run-name: ${{ github.actor }} is doing CICD with Serverless

on: 
  # Trigger the workflow on push events to the main or any other branch
  push: 
    branches: [main, "*"]

jobs:
  # This job installs dependencies
  install-dependencies:
    runs-on: ubuntu-latest # Use the latest Ubuntu virtual machine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3 # GitHub action to check out the code
      - name: Run Installation of Dependencies Commands
        run: npm install # Install project dependencies

  # This job runs unit tests
  unit-tests:
    runs-on: ubuntu-latest # Also runs on an Ubuntu machine
    needs: install-dependencies # Depends on the successful completion of the install-dependencies job
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3 # Check out code again
      - name: Run Installation of Dependencies Commands
        run: npm install # Install dependencies again to ensure a clean environment
      - name: Run Unit Tests
        run: npm test # Run the project's unit tests 